package com.lazy.pegasus.core.utils;

import com.lazy.pegasus.core.common.SpanString;

import java.util.Random;

public class RandsUtil {

    private static final Random rands = new Random(System.currentTimeMillis());

    public static Random getRands() {
        return rands;
    }

    /**
     * @return a randomized UUID generated by java as string.
     */
    public static String randUUID() {
        return java.util.UUID.randomUUID().toString();
    }

    /**
     * @return a randomized UUID generated by java as {@link SpanString}
     */
    public static SpanString randUUIDAsSpanString() {
        return SpanString.of(randUUID());
    }

    /**
     * @param len length of bytes array need to random.
     * @return a randomized byte array.
     */
    public static byte[] randBytes(int len) {
        byte[] bytes = new byte[len];
        rands.nextBytes(bytes);

        return bytes;
    }
}
