package com.lazy.pegasus.core.utils;

import com.lazy.pegasus.core.common.SpanString;

public class RandsUtil {

    /**
     * @return a randomized UUID generated by java as string.
     */
    public static String randUUID() {
        return java.util.UUID.randomUUID().toString();
    }

    /**
     * @return a randomized UUID generated by java as {@link SpanString}
     */
    public static SpanString randUUIDAsSpanString() {
        return SpanString.of(randUUID());
    }
}
